DECLARE @M INT, @MES VARCHAR(20)

SET @M = MONTH(GETDATE())
-- GETDATE() arroja la fecha actual
-- MONTH(fecha) arroja el mes de una fecha dada

SET @MES = (
	CASE @M
		WHEN 1 THEN 'ENERO'
		WHEN 2 THEN 'FEBRERO'
		WHEN 3 THEN 'MARZO'
		WHEN 4 THEN 'ABRIL'
		WHEN 5 THEN 'MAYO'
		WHEN 6 THEN 'JUNIO'
		WHEN 7 THEN 'JULIO'
		WHEN 8 THEN 'AGOSTO'
		WHEN 9 THEN 'SETIEMBRE'
		WHEN 10 THEN 'OCTUBRE'
		WHEN 11 THEN 'NOVIEMBRE'
		WHEN 12 THEN 'DICIEMBRE'
		ELSE 'NO ES MES VÁLIDO'
	END
)

PRINT @MES
